name: collision_check
description: 效率超高的碰撞检测插件，适用于所有Flutter平台
version: 0.0.1
author: hahafather007
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
